### ISSUE TITLE
DOC: Update Salesforce Initial Setup + Configuration (For Administrators) Wiki Pages

### ISSUE THREAD

**Issue by eehjunggnujhee** [SFDO-Community-Sprints/GrassRootsMobileSurveyApp#30]
[Slack Link of the converation](https://salesforce-external.slack.com/archives/C01TLP7BN9K/p1620994892020500)

GRMS team made several suggestions to improve the installation documentation during the March mini-sprint. The plan is to update the doc before the June sprint.

[Google Doc](https://docs.google.com/document/d/14CQrP2y631f6i-jtEYCP3NqEuphqI5I9e_9UAccJp8U/edit#heading=h.eldn7tnb547m)

**Comment by shunkosa** [comment]
Sorry for the delay. Thank you so much!! Looks great to me. Trish will organize the other doc improvements in the next community sprint.
