### ISSUE TITLE
Add heroku url screen for easier setup

### ISSUE THREAD

**Issue by shunkosa** [SFDO-Community-Sprints/GrassRootsMobileSurveyApp#32]
### Problem
Currently, there's a lot of technical steps to setup mobile app.

### Proposed solution
Add a new screen to set heroku url inside the mobile app. In this case, we can distribute generic `.apk` file.
https://docs.google.com/presentation/d/1fJ6WqEiahUMUkd8iMjq9LV4Tgat-hUMWzPuuN8wIwsA/edit

**Comment by richathifi** [comment]
A couple user stories stories against this issue:
 - An admin can configure their users' apps without needing the command line
 - An app user can re-open their app without scanning a QR code (maybe this already works - but I have to do it every time)

**Comment by shunkosa** [comment]
Thanks! In my understanding, this activity is a part of the roadmap #34
