### ISSUE TITLE
Client Record Type is not being respected in the Junction Object 

### ISSUE THREAD

**Issue by travelertrish** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#39]
<img width="1417" alt="2021-07-01_17-35-10" src="https://user-images.githubusercontent.com/2277732/124519466-68af3a80-ddb7-11eb-9c4b-d66022bc3f15.png">
Noted by @melissahilldees: 
In the Junction Object, when bringing up clients, the field does not limit the list to those with the Client Record Type.

**Comment by shunkosa** [comment]
@travelertrish @melissahilldees Thanks. This is known restriction. Currently, Salesforce doesn't support lookup filter based on record type developer name. https://trailblazer.salesforce.com/ideaView?id=08730000000krFAAAY
Another idea is that include an Apex trigger to prevent from saving unexpected record type records to the field.

**Comment by shunkosa** [comment]
Ah, sorry, we can use validation rule.

**Comment by shunkosa** [comment]
This is implemented at https://github.com/SFDO-Community-Sprints/GrassrootsSurveySalesforcePackage/commit/9e12790b4c439c2fda576c5c73064af8a8d333aa and will be included in the next version.
