### ISSUE TITLE
Missing field in Sample Surveys Metecho Epic - "GRMS_Survey__c.respondant_First_Name__c"

### ISSUE THREAD

**Issue by D-McGovern** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#65]
I'm unable to create a Scratch org in Metecho and receive this error:

Uh oh. There was an error creating your new Scratch Org for Epic “Sample Surveys.”
cumulusci.salesforce_api.exceptions.MetadataParseError: Could not process MDAPI response: Update of PermissionSet GRMS_App_Admin: Error: In field: field - no CustomField named GRMS_Survey__c.Respondant_First_Name__c found

It sounds as though the name of this field was changed and needs to be resolved manually

**Comment by eehjunggnujhee** [comment]
Fix delivered in feature/metecho branch
