### ISSUE TITLE
Update Documentation for package w/out Record Types

### ISSUE THREAD

**Issue by kdveverka** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#73]

**Comment by shunkosa** [comment]
I updated screenshots and remove record type and 'Survey User' term. Can you pleas review? @travelertrish @johncastelloe 
Feel free to update the page directly.
https://github.com/SFDO-Community-Sprints/GrassrootsMobileSurveyApp/wiki/Salesforce-Initial-Setup
