### ISSUE TITLE
Bug: Beta v0.11 - Mobile Client still looking for record types

### ISSUE THREAD

**Issue by kdveverka** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#74]
From Jung: 
 I see the mobile app is searching for record type. Let us know if there is an updated version; otherwise, we can wait. Than kyou
[ERROR] Sun Mar 06 2022 17:26:37 GMT-0800 (PST) | fetchSalesforceRecords |
[
  {
    "message": "\n'eehjunggnujhee@gmail.com' AND RecordType.DeveloperName = 'GRMS_User'\n                               ^\nERROR at Row:1:Column:88\nDidn't understand relationship 'RecordType' in field path. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names.",
    "errorCode": "INVALID_FIELD"
  }
]

**Comment by shunkosa** [comment]
I republished the apk file again. Hope this works🙏 https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40shunkosa/grassroots-mobile-survey-app-ce571634fa6646af8d328cdf4a2d0e70-signed.apk

**Comment by shunkosa** [comment]
Code is here https://github.com/SFDO-Community-Sprints/GrassrootsMobileSurveyApp/commit/67f06f7e66e5d2232c2a3cecb7258b57900bc5db

**Comment by kdveverka** [comment]
This is resolved.
