### ISSUE TITLE
Validation Rules on User & Client Relationship object need correction

### ISSUE THREAD

**Issue by kdveverka** [SFDO-Community-Sprints/GrassrootsMobileSurveyApp#75]
The two validation rules on the User and Client Relationship object contain typos. They say TEXT(GRMS_Client__r.GRMS_ContactType__c) <> "Survey_Client" for one and TEXT(GRMS_User__r.GRMS_ContactType__c) <> "Survey_User" for the other. They need to be corrected to have "Survey Client" and "Survey User" at the end (remove the underscores in the picklist choice names).

**Comment by shunkosa** [comment]
Fixed here https://github.com/SFDO-Community-Sprints/GrassrootsSurveySalesforcePackage/pull/12/commits/1b0d13ab6e2e4e14d5218dfbb2b589d6c9aebf3d

**Comment by shunkosa** [comment]
Let me close this issue because the fixed version was merged and published as 0.11.0-3.
